export const AUCTION_DURATION_SECONDS = 10;
export const AUCTION_DURATION_MS = AUCTION_DURATION_SECONDS * 1000;
export const THREE_MINUTES_IN_MS = 3 * 60 * 1000;
export const HOUR_IN_MS = 60 * 60 * 1000;

export default {
  THREE_MINUTES_IN_MS,
  AUCTION_DURATION_SECONDS,
  AUCTION_DURATION_MS,
  HOUR_IN_MS,
};
